name: 'Renew Hax'

on:
  workflow_dispatch:
  schedule:
    - cron: '19 17 */2 * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Renewing Hax VPS ....' 
        shell: cmd
        env:
          SECRET_USERNAME: ${{ 1886409565 }}
          SECRET_PASSWORD: ${{ Wang584521 }}
        run: |
         curl -sSL -O https://github.com/King-stark/Hax_extend/raw/main/HaxAutoReNew.exe
         HaxAutoReNew.exe -user "%SECRET_USERNAME%" -password "%SECRET_PASSWORD%"
